### ISSUE TITLE
Results on ImageNet

### ISSUE THREAD

**Issue by hixiaye** [yuhuixu1993/PC-DARTS#1]
hi @yuhuixu1993 thanks for sharing your excellent work. I just wonder the search cost when you search on ImageNet.
PC-DARTS uses 12.5% images of Imagenet for searching in 4.3, so would the search cost be 3.8*8=30.4 GPU-days,  if we use 100% images of ImageNet? 
thx

**Comment by yuhuixu1993** [comment]
@sxs11 Hi，if we use the whole ImageNet dataset, it takes about 10 GPU days (batch-size 2048, 1:1 for train and validation dataset), it may take less time when channel proportion K=4. While a subset of ImageNet is enough for searching a good architecture, other works such as FBNet also uses a subset of ImageNet.
