### ISSUE TITLE
about random sample

### ISSUE THREAD

**Issue by IDKiro** [yuhuixu1993/PC-DARTS#10]
In sec 4.1, you said:

```
instead choose the first K channels of xi for operation mixture directly. To compensate, after xj is obtained, we shuffle its channels before using it for further computations.
```

but i think it is not a random sample implement because choosing the first K channels and channel shuffle are all determined operation.

i'm glad that you tell me if there is any misunderstanding of the implementation.

**Comment by Catosine** [comment]
I think after channel shuffle then you will get a "random" sample
GL,

**Comment by yuhuixu1993** [comment]
@IDKiro , hi, sorry for the late reply. Random sampling also works for our methods while channel-shuffle as a proxy operation may obtain slightly better performance. Besides, we have also upload the implementation of random sampling in the file `model_search_random.py` for your consideration.

**Comment by IDKiro** [comment]
Thanks very much for your reply.
