### ISSUE TITLE
model 'genotype' has no attribute 'DARTS'

### ISSUE THREAD

**Issue by ldd91** [yuhuixu1993/PC-DARTS#12]
I exec 'python train.py --auxiliary --cutout' and run an error which logs shows：
File “train.py ” line 72,in main
File "<string>",line 1,in <module>
AttributeError: module 'genotypes' has no attribute 'DARTS'
My pytorch version is 1.1.0 python version is python3

**Comment by yuhuixu1993** [comment]
Please check that the default '--arch' is 'PC-DARTS' not 'DARTS'

**Comment by ldd91** [comment]
Thank you for reply,I change the --arch to PCDARTS and it works
