### ISSUE TITLE
How can i import the network and weights in a different script ?

### ISSUE THREAD

**Issue by cristyioan2000** [yuhuixu1993/PC-DARTS#14]
Hello, 

I want to load the found architecture in a different script, is there a way to load the architecture structure(class) and the .weight file externally, just by importing using torch.load() ? 

Thanks

**Comment by yuhuixu1993** [comment]
@cristyioan2000, I think you may need to add the structure file as the model.py, e.g. resnet.py and import the structure in the training file.

**Comment by cristyioan2000** [comment]
I was thinking that I can create a checkpoint file 
```
checkpoint_file = {
'model': Some_Model_Class(),
'weights':model.state_dict()
} 
torch.save(checkpoint_file,'architecture.pth')
```
I'm going to try both ways and post the result.
