### ISSUE TITLE
Can i use this method with a [3x320x320] img shape on a Nvidia 1080ti 11GB ? 

### ISSUE THREAD

**Issue by cristyioan2000** [yuhuixu1993/PC-DARTS#18]
Hello,

I am trying to find an architecture for a 3x320x320 input image set as my dataset. I keep getting out of memory error from CUDA. Is it possible to run this NAS method for this image resolution using only 1 x Nvidia 1080ti 11GB ?

**Comment by yuhuixu1993** [comment]
hi， @cristyioan2000 , I think it would be ok if you use a smaller batch-size, while the time cost will be increased.

**Comment by cristyioan2000** [comment]
The only batch-size i can run is 2 for this image size. I guess that's not so good because the batchnorm does nothing.

**Comment by yuhuixu1993** [comment]
For imagesize as big is as 320， I recommend you use the supernet we adopt to search on imagenet in model_search_imagenet.py which is different from that we use in cifar(three 2x downsampling layers in the beginning) . I think if you use this architecture， batch-size can be larger.

**Comment by cristyioan2000** [comment]
If I want to search an architecture for a custom dataset is it enough to use `train_search.py` using the architecture from `model_search_imagenet.py` ? 
```
# file:  train_search.py
# from model_search import Network
from model_search_imagenet import Network
```

**Comment by yuhuixu1993** [comment]
Hi，yes. But the data processing is also necessary to be replaced. Learning rate, batch-size should be suitable for your data.
