### ISSUE TITLE
text error in the paper about network parameters freeze

### ISSUE THREAD

**Issue by bolianchen** [yuhuixu1993/PC-DARTS#19]
The following description is extracted from Section 4.2:
we freeze network hyper-parameters and
only allow network parameters to be tuned **in** the first 15 epochs

I guess the authors wanted to say the parameters are allowed to be tuned only after the first 15 epochs, which is consistent with the codes.

**Comment by yuhuixu1993** [comment]
@bolianchen ，hi，thanks. We will update the description in the paper for more clarity.
