### ISSUE TITLE
parallel train_search code on ImageNet

### ISSUE THREAD

**Issue by EvanJamesMG** [yuhuixu1993/PC-DARTS#2]
hi, @yuhuixu1993, thanks for your good work.
You mentioned "We use eight Tesla V100 GPUs for search, and the total batch size is
1,024. The entire search process takes around 11.5 hours. " 
I just wanna to know  do you have any plan to realease your parallel train_search code on ImageNet ? Thank you.

**Comment by yuhuixu1993** [comment]
Hi, @EvanJamesMG we have uploaded the code for the search on imagenet(model_search_imagenet.py). The main function can be easily modified from the training file for CIFAR10. We will upload it after the code is cleaned. Thanks.
