### ISSUE TITLE
About search cost in imagenet

### ISSUE THREAD

**Issue by HMQstu** [yuhuixu1993/PC-DARTS#20]
"PC-DARTS allows a direct search on ImageNet (while DARTS failed due to low
stability), and achieves a state-of-the-art top-1 error of 24.2% (under the mobile setting) with only
3.8 GPU-days (11.5 hours) on 8 GPUs for search"   the sentence means what？

if use a single gpu, it is 3.8GPUS-days ; if use 8 gpus, it is 11.5 hours ?

**Comment by yuhuixu1993** [comment]
@HMQstu ，We use 8 GPUs and 8*11.5=3.8GPU-days， thanks.

**Comment by HMQstu** [comment]
Thanks for your responses
