### ISSUE TITLE
why did you discard parameter '--unrolled'? 

### ISSUE THREAD

**Issue by xingyueye** [yuhuixu1993/PC-DARTS#23]
@yuhuixu1993 hi, I just noticed that you have dropped the parameter '--unrolled' after 'python train_search.py' command  in ReadME. I want to know it's a carefulless missing or you truely did it.  After all, the derivation of architecture parameters will be incomplete without '--unrolled'.

**Comment by yuhuixu1993** [comment]
As claimed in the paper, our method is constructed based on DARTS (1st order) (unrolled=false), as sencond order .may not bring much performance gain but slower. Most of recent works based on darts prefer DARTS (1st order), such as PDARTS, DASRT+.
