### ISSUE TITLE
randomness involved in the channel_shuffle function?

### ISSUE THREAD

**Issue by bolianchen** [yuhuixu1993/PC-DARTS#28]
Hi @yuhuixu1993,

It seems the channel_shuffle function evenly redistributes the channels composed of those pass through mixed operations (the first 1/K) and those do not (the later 1-1/K) in a determined pattern. Although it can produce much more complex results in later nodes as more channel_shuffle functions contribute, there is no randomness involved. Is it possible for the network to get used to the pattern and lose the regularization effect eventually. Why didn't you apply random sampling? Thank you!

    def channel_shuffle(x, groups):
        batchsize, num_channels, height, width = x.data.size()
        channels_per_group = num_channels // groups
        # reshape
        x = x.view(batchsize, groups,
                   channels_per_group, height, width)
        x = torch.transpose(x, 1, 2).contiguous()
        # flatten
        x = x.view(batchsize, -1, height, width)
        return x

In my toy example:

    x = torch.Tensor([ [ [ [1,1,1], [1,1,1], [1,1,1] ],
                         [ [2,2,2], [2,2,2], [2,2,2] ],
                         [ [3,3,3], [3,3,3], [3,3,3] ],
                         [ [4,4,4], [4,4,4], [4,4,4] ],
                         [ [5,5,5], [5,5,5], [5,5,5] ],
                         [ [6,6,6], [6,6,6], [6,6,6] ],
                         [ [7,7,7], [7,7,7], [7,7,7] ],
                         [ [8,8,8], [8,8,8], [8,8,8] ] ] ])

the output of channel_shuffle(x, 4) is always

    tensor([[[[1., 1., 1.],
              [1., 1., 1.],
              [1., 1., 1.]],

             [[3., 3., 3.],
              [3., 3., 3.],
              [3., 3., 3.]],

             [[5., 5., 5.],
              [5., 5., 5.],
              [5., 5., 5.]],

             [[7., 7., 7.],
              [7., 7., 7.],
              [7., 7., 7.]],

             [[2., 2., 2.],
              [2., 2., 2.],
              [2., 2., 2.]],

             [[4., 4., 4.],
              [4., 4., 4.],
              [4., 4., 4.]],

             [[6., 6., 6.],
              [6., 6., 6.],
              [6., 6., 6.]],

             [[8., 8., 8.],
              [8., 8., 8.],
              [8., 8., 8.]]]])

**Comment by yuhuixu1993** [comment]
@bolianchen ，hi，you can check in the readme file we have a totally random version released.

**Comment by bolianchen** [comment]
Hi @yuhuixu1993 

Thanks for your explanation. I will check the details.

Best,
Bolian
