### ISSUE TITLE
Typo at model_search_imagenet.py

### ISSUE THREAD

**Issue by Catosine** [yuhuixu1993/PC-DARTS#3]
Hello, @yuhuixu1993 

Should [the #L130 from model_search_imagenet.py](https://github.com/yuhuixu1993/PC-DARTS/blob/master/model_search_imagenet.py#L130) be changed as:
`reduction_prev = False`

Thanks,

**Comment by yuhuixu1993** [comment]
Hi, this is not a typo. reduction_prev indicates that if previous layer is a reduction layer(stride=2). In the search on ImageNet, the stem cells are reductions cells thus reduction_prev = True which is the difference from search on CIFAR.

**Comment by Catosine** [comment]
I see. Thanks!

**Comment by Catosine** [comment]
I just noticed that [#L130](https://github.com/yuhuixu1993/PC-DARTS/blob/master/model_search_imagenet.py#L130) does not matter. Based on [#131-136](https://github.com/yuhuixu1993/PC-DARTS/blob/master/model_search_imagenet.py#L131-#L136), for the first iteration, i = 0 so reduction_prev will be False. But this is different from your idea, for the stem cells will not be considered as reduction cells.

So should I forced the reduction_prev to be True for the very first cell?

Thanks!
