### ISSUE TITLE
train_search_imagenet lr scheduler is weird

### ISSUE THREAD

**Issue by andyhahaha** [yuhuixu1993/PC-DARTS#33]
Hi @yuhuixu1993 ,

I am trying to run train_search_imagenet.
But I find that the learning rate decay is weird.
if the initial_lr is 0.5 and there is Warming-up Epoc.
The lr should be 0.1, 0.2, 0.3, 0.4, 0.5, 0.49xxx, 0.49xxxx.....
However, the lr become 0.1, 0.04, 0.024, 0.018, ...
It seems that you times 1/5, 2/5, 3/5, ... on previous lr not on the initial_lr 0.5 
Am I right?

**Comment by yuhuixu1993** [comment]
@andyhahaha , hi, thanks for pointing out, I have changed the code, please check if it is right now.

**Comment by andyhahaha** [comment]
It right! 
Thanks for your great work!
