### ISSUE TITLE
Using 1080Ti and python2 pytorch1.0 out of memory

### ISSUE THREAD

**Issue by appleleaves** [yuhuixu1993/PC-DARTS#35]
I run the code as suggested but fail to get the code running but get an error "out of memory".

Envs:
I use one GPU 1080TI with 11178MiB.
I use python2.7 and PyTorch 1.0.
I simply download the code and run python train_search.py.

Would you please tell me where I went wrong?

**Comment by yuhuixu1993** [comment]
@appleleaves ，hi，you may try pytorch version 0.3
