### ISSUE TITLE
关于在imagenet数据集上训练的相关咨询

### ISSUE THREAD

**Issue by malizheng** [yuhuixu1993/PC-DARTS#38]
你们使用的imagenet数据集是ILSVRC2012（大概压缩包有150G）吗？你们基于什么配置在imagenet数据集下训练搜索出来的最佳模型呢？总共花多长时间呢？

**Comment by yuhuixu1993** [comment]
You may refer to our paper for detailed descriptions about the experiments and Datasets. The data set is ILSVRC2012, we searched on the sampled dataset and evaluate on the whole dataset. The search time cost 11.5 hours with 8 GPUs.

**Comment by malizheng** [comment]
Okay, thank you very much. I would like to ask how long it took to evaluate on the whole dataset.

**Comment by yuhuixu1993** [comment]
It takes about 3 days to evaluate on ImageNet with 8 V100 GPUs and the time would be shorter if you use DALI.
