### ISSUE TITLE
pytorch vision

### ISSUE THREAD

**Issue by pawopawo** [yuhuixu1993/PC-DARTS#4]
Tesla V100 which requires CUDA_VERSION >= 9000 for optimal performance and fast startup time, but your PyTorch(0.3.1) was compiled with CUDA_VERSION 8000.

**Comment by yuhuixu1993** [comment]
Hi,  @xxsgcjwddsg I have uploaded the train_search file for higher version python on V100. If there are any typos, please contact me. Thanks
