### ISSUE TITLE
How to change the channel proportion K? 

### ISSUE THREAD

**Issue by anujmhr** [yuhuixu1993/PC-DARTS#46]
It seems to be hardcoded. Do you just modify the following lines to change the parameter K? 
 

https://github.com/yuhuixu1993/PC-DARTS/blob/2f6aac375ada8aca3b9cbf782e456f8ce7e0243a/model_search.py#L33-L35
https://github.com/yuhuixu1993/PC-DARTS/blob/2f6aac375ada8aca3b9cbf782e456f8ce7e0243a/model_search.py#L42-L43

https://github.com/yuhuixu1993/PC-DARTS/blob/2f6aac375ada8aca3b9cbf782e456f8ce7e0243a/model_search.py#L50

**Comment by yuhuixu1993** [comment]
@anujmhr ,yes, you are right. I will give some notations.

**Comment by anujmhr** [comment]
@yuhuixu1993 thank you
