### ISSUE TITLE
有一个小bug

### ISSUE THREAD

**Issue by shuangjian24** [yuhuixu1993/PC-DARTS#5]
当开始train_search.py的时候，会不停的创建log.txt，但事实上应该是只有第一个创建的txt是有效的。之后会不停的创建log文件，并且这些文件都是空的

**Comment by yuhuixu1993** [comment]
@shuangjian24，hello，您用的环境能不能和我说下，python版本和pytorch 版本

**Comment by yuhuixu1993** [comment]
@shuangjian24 ，hi，I guess you run our codes on windows, it may cause some errors with the logging function. We recommend to run the codes on Linux.

**Comment by shuangjian24** [comment]
windows//python3.7.0//pytorch.1.1.0
