### ISSUE TITLE
Understanding the two sets of the architecture hyperparameter

### ISSUE THREAD

**Issue by slyviacassell** [yuhuixu1993/PC-DARTS#52]
Thank you very much for your opensource! And I may have some misunderstanding of the description of the architecture hyperparameter. The description is as follow:
In other words, for edge <img src="http://chart.googleapis.com/chart?cht=tx&chl=(i,j)" style="border:none;">, given an input <img src="http://chart.googleapis.com/chart?cht=tx&chl=x_i" style="border:none;">, the difference from using two sets of hyper-parameters <img src="http://chart.googleapis.com/chart?cht=tx&chl=\{\alpha_{i,j}^{o}\}" style="border:none;"> and <img src="http://chart.googleapis.com/chart?cht=tx&chl=\{\alpha_{i,j}^{'o}\}" style="border:none;"> is largely reduced, because only a small part <img src="http://chart.googleapis.com/chart?cht=tx&chl=1/K" style="border:none;"> of input channels would go through the operation mixture while the remaining channels are left intact.

- Did this means that the PC-Darts makes the searching results more reproducible? 
- Why and how this method regularize the preference of the weight-free operation?

Could anybody can explain it?
Thank you very mch!

**Comment by yuhuixu1993** [comment]
Hi, sorry for late reply,. I can answer the second question. In our extended journal version, we have proven that channel sampling is equivalent to adding a regularization term on both weights and architectural parameters which prevent the supernets from overfitting.

**Comment by slyviacassell** [comment]
Thanks, I will look forward to your extended version.
