### ISSUE TITLE
how you report the final accuracy in evaluation? Possibly touch the test set for the best acc?

### ISSUE THREAD

**Issue by d12306** [yuhuixu1993/PC-DARTS#53]
@yuhuixu1993 , hi, thanks for your great work!

I notice that you track the best accuracy during evaluation in CIFAR-10/100, I am wondering how do you report the final accuracy in the paper? Do you report the best acc or the acc at the last epoch?

Thanks,

**Comment by yuhuixu1993** [comment]
@d12306, hi, I report the best accuracy. The result is the mean of three independent runs.

**Comment by d12306** [comment]
sure, thanks.
