### ISSUE TITLE
Searched genotype remain / keep unchanged for a great number of epoch

### ISSUE THREAD

**Issue by rrryan2016** [yuhuixu1993/PC-DARTS#56]
Hello,

Thanks for your great work and kind sharing. 

Though, I got some doubt here, when I am running the search stage code of PC-DARTS on a classification task of customized dataset, the searched genotype in the first 35 epoch remain the same as

`genotype = Genotype(normal=[('avg_pool_3x3', 1), ('max_pool_3x3', 0), ('dil_conv_3x3', 1), ('max_pool_3x3', 2), ('sep_conv_3x3', 0), ('dil_conv_3x3', 3), ('skip_connect', 4), ('dil_conv_5x5', 3)], normal_concat=range(2, 6), reduce=[('dil_conv_3x3', 0), ('dil_conv_5x5', 1), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 3), ('sep_conv_3x3', 1), ('dil_conv_3x3', 3), ('max_pool_3x3', 4)], reduce_concat=range(2, 6))`

while I use the original DARTS(https://github.com/quark0/darts) on the same task, the genotype of each contiguous epoch varies. 

Based on your experience, is it normal, or somewhere I ignore, or which hyper-parameter could I pay attention to?

Thanks in advance. 😄

**Comment by yuhuixu1993** [comment]
Hi, thanks for your attention of our work, we use the first few epochs to warm up the supernet without training arch parameters. You can set the corresponding hyper para in the 156th line of the train_search.py file

**Comment by rrryan2016** [comment]
> 6th line of the train

Thanks for the reply, my problem solved.
