### ISSUE TITLE
ImageNet search question

### ISSUE THREAD

**Issue by pawopawo** [yuhuixu1993/PC-DARTS#6]
"To reduce search time, we randomly sample two subsets from the 1.3M training set of ImageNet, with 10% and 2.5% images, respectively. The former one is used for training network weights and the latter for updating hyper-parameters." I have two questions:
1. 10% images of ImageNet means the subset only has 100 classes? 
2. hyper-parameters means architecture weights?
Thanks for your reply!

**Comment by yuhuixu1993** [comment]
@xxsgcjwddsg ,the subset still has 1000 classes. Actually, we sampled 10% and 2.5% from each class for training and validation respectively. Yes, hyper-parameters are architecture weights.

**Comment by pawopawo** [comment]
> @xxsgcjwddsg ,the subset still has 1000 classes. Actually, we sampled 10% and 2.5% from each class for training and validation respectively. Yes, hyper-parameters are architecture weights.

Thanks.
How do you search with multiple GPUs? I add model = nn.DataParallel(model) before model = model.cuda() and model = model.module after it, but still search on one GPU.

**Comment by yuhuixu1993** [comment]
@xxsgcjwddsg ,you need to comment this line `torch.cuda.set_device(args.gpu)`

**Comment by pawopawo** [comment]
> @xxsgcjwddsg ,you need to comment this line `torch.cuda.set_device(args.gpu)`

![image](https://user-images.githubusercontent.com/38682321/61710414-3780ff80-ad84-11e9-95e3-56f60ea274b5.png)
Thanks !
I has comment torch.cuda.set_device(args.gpu), but  don't work.

**Comment by yuhuixu1993** [comment]
Can you show the errors? I think maybe the error still comes from the model.module?  E.g. in the SGD optimizer, it should be `model.parameters()`not model.module.parameters(). Besides, do you change the model.module in the train function and validation function?

**Comment by pawopawo** [comment]
Thanks a lot.
I shouldn't add "model = model.module"  after  "model = nn.DataParallel(model).cuda()"

**Comment by xxsgcjwddsg** [comment]
> Can you show the errors? I think maybe the error still comes from the model.module? E.g. in the SGD optimizer, it should be `model.parameters()`not model.module.parameters(). Besides, do you change the model.module in the train function and validation function?
[log.txt](https://github.com/yuhuixu1993/PC-DARTS/files/3424720/log.txt)
According the paper, architecture hyper-parameters are frozen during the first 35 epochs. However, 
After searching for 35 epochs, the search seems to be very slow. It’s been eight hours, not updated yet. (search in ImageNet100)

**Comment by pawopawo** [comment]
![image](https://user-images.githubusercontent.com/38682321/61761960-ff6cd180-ae02-11e9-8a70-ef23e5348287.png)
Hi, when run architecture.step(), it encountered an error of OOM.
Thanks for your reply!

**Comment by yuhuixu1993** [comment]
@xxsgcjwddsg ，just for sure that you use 8 v100gpus. Besides，I notice that your parameter size is nearly two times of mine, how many layers are stacked in the search period? We use 8 in our experiments. And the initial channels are 16.

**Comment by pawopawo** [comment]
![image](https://user-images.githubusercontent.com/38682321/61778942-5d64dd80-ae32-11e9-8f22-9e6d314125b3.png)
Thanks for your reply.
I use 8 v100 gpus, but the first one takes up most. As the picture shows，the batch size is 256. 
I think the reason is using self.model.module._loss(input, target).  However, it will run only on one GPU.

**Comment by yuhuixu1993** [comment]
@xxsgcjwddsg ，hi，maybe you need to remove the `.to(..... .device)` e.g. to(xtemp.device) code in the model_search_imagenet.py. I run this code in the company， may be there are differences within devices. If it worked, please tell me and  I will update the code.

**Comment by pawopawo** [comment]
![image](https://user-images.githubusercontent.com/38682321/61787208-e8010900-ae41-11e9-9e4d-8b4723d0c469.png)
Thanks for your reply. It cann't works. 
I have another question. The paper randomly sample two subsets from the 1.3M training set of ImageNet, with 10% and 2.5% images, respectively.  The batch_size of valid_queue is also 1024? If it is 1024, then the frequency of architect.step() is 1/4 of optimizer.step()?

**Comment by yuhuixu1993** [comment]
@xxsgcjwddsg ,hi, I have no idea now, I can run the code with 8 V100(16G each). Maybe you can add my wechat, we can talk about more details. Yes, and I also change the validation batch-size to balance the frequency and found no difference. Which version of pytorch you use by the way？

**Comment by HeathHose** [comment]
@yuhuixu1993,  hi. I notice that  the validation batch-size  is same as the train batch-size.According to my understanding, it means that the valid dataset will be used four times?
Or another way， architect  steps one time while optimizer steps four times?
