### ISSUE TITLE
The node number in the imagenet cell

### ISSUE THREAD

**Issue by ddghost** [yuhuixu1993/PC-DARTS#9]
In the paper, each imagenet cell consists of N = 6 nodes. Why the default setting of the node number in the code is 4?

**Comment by yuhuixu1993** [comment]
@ddghost , hi, 6 nodes in the paper include two input nodes c(k-1) and c(k-2). Node number in the code indicates the number of the nodes(excluding the input nodes).

**Comment by ddghost** [comment]
Thanks for the reply,
